### ISSUE TITLE
No handler defined for /devices/wb-adc/controls/Vin

### ISSUE THREAD

**Issue by pivadm** [nzfarmer1/mqtt2opcua#5]
Hello, please help.

What is mean this message 
No handler defined for /devices/wb-adc/controls/Vin.
The first data from first topic is received, but then error appear:

MQTT onMessage: /devices/wb-adc/controls/A1 (5 bytes)
MQTT onMessage: /devices/wb-adc/controls/A1/meta/order (1 bytes)
No handler defined for /devices/wb-adc/controls/A1/meta/order

Regards.

**Comment by nzfarmer1** [comment]
Did you add a forward.on('devices/wb-adc/controls/A1/meta/order',...)?

**Comment by pivadm** [comment]
I want to forward all topics '#'

Иван Поспелов

16 марта 2017 г. 12:12 AM пользователь "Andrew McClure" <
notifications@github.com> написал:

Did you add a forward.on('devices/wb-adc/controls/A1/meta/order',...)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nzfarmer1/mqtt2opcua/issues/5#issuecomment-286880764>,
or mute the thread

**Comment by pivadm** [comment]
Hello,  thank you. You drive me to right settings. I added forward.on('/#') and all working.

**Comment by hoblins** [comment]
Hello,
I have the same (or similar?) issue, but couldn't solve it.

In the example, I set:
`forward.on("#", ...`
`backward.on("#", ...`
`topics:['#']`
The MQTT topics I have to use don't have a leading slash ('/').

The forwarding to OPC UA works just one single time. Every following MQTT message raises an error, see part from log:

> 0|mqtt2opc | **MQTT onMessage: topic1/var1** (4 bytes)
0|mqtt2opc | Creating folders for new topic: topic1/var1
0|mqtt2opc | run.js / forward.on 1234
0|mqtt2opc | run.js / forward.on 1234
0|mqtt2opc | OPCUA Get: topic1/var1
0|mqtt2opc | run.js / forward.on 1234
0|mqtt2opc | **MQTT onMessage: topic1/var1** (4 bytes)
0|mqtt2opc | No handler defined for topic1/var1
0|mqtt2opc | **MQTT onMessage: topic1/var1** (4 bytes)
0|mqtt2opc | No handler defined for topic1/var1
0|mqtt2opc | **MQTT onMessage: topic2/var1** (4 bytes)
0|mqtt2opc | No handler defined for topic2/var1
0|mqtt2opc | **MQTT onMessage: topic2/var1** (4 bytes)
0|mqtt2opc | No handler defined for topic2/var1

**Comment by nzfarmer1** [comment]
Ah. Ok. this is interesting.  I haven't checked the library for a while, but I recall that we prepended a "/" to  topics without a leading "/" in order to standardise the starts.

This may imply that a leading "/" is required even if one was not specified in the original topic.    I haven't got a test rig set up, but please test and report back.

On a general note, I understand that the MQTT crowd is a little down on a leading "/" but there it is.  Perhaps there is scope for a change to remove/replace the leading "/" rather than prepend to those topics with out.
